### ISSUE TITLE
[Sonoma image] Installation cannot proceed because the installer is damaged

### ISSUE THREAD

**Issue by goekce** [Pyenb/macOS-ISOs#1]
On a Linux machine I setup Virtualbox for macOS using the following instructions:
- https://www.xda-developers.com/how-install-macos-virtualbox/
- https://apple.stackexchange.com/questions/435574/monterey-vm-reboot-loop-and-kernel-panic-in-virtualbox-6-1-32-on-apple-host-har
- additionally activating USB3 (otherwise no mouse or keyboard control)

I downloaded and checked the checksum:

> 62a6a1db4aec3717385ef04b477ab00c

I formatted the virtual harddisk using Disk Utility and proceeded with installation. After ~3 minutes I got the following error:

> Installation cannot proceed because the installer is damaged. Redownload the installer and try again.

I will try the installation with another ISO. 

Did someone else encounter a similar error?

**Comment by goekce** [comment]
> I will try the installation with another ISO.
It is hard to find a non-corrupted file. I give up.

**Comment by Pyenb** [comment]
Hm, weird. The Sonoma Image should be the exact same one that I am running right now as a Proxmox VM. Give me a minute and I'll try and see if I can reproduce the error. If yes, I will recreate and reupload the ISO.

**Comment by Pyenb** [comment]
I am currently recreating the installer with MIST, even tough the installation seemed to work fine for me. 

But if you have trouble finding another installer, check archive.org, that's where I got my installer from.

https://archive.org/details/macos-ventura-and-sonoma

**Comment by Pyenb** [comment]
I reuploaded the Sonoma ISO now. Maybe check again, if that isn't working, download from archive.org. If nothing works, than it's more likely that the problem is on your side

**Comment by goekce** [comment]
If you are running the same image, then the problem should be on my side. 

I noticed later that I don't need the image anymore. My goal was to emulate Apple M2 on x86_64 but I noticed this is currently impossible :/

☺️ thanks a lot Ben!

**Comment by autra** [comment]
FWIW I have the same issue, with the current image (md5sum: f628fa331e47c09ab8b9f1075744512c). Most probably something wrong with virtualbox or vm settings...

**Comment by mc510** [comment]
I also am having this issue, with Sonoma image downloaded last night. Tried setting system date back six months, but no joy. Curious if same issue will arise with other macOS versions, or if this is unique to Sonoma.

**Comment by Pyenb** [comment]
Hm, that's weird. I just downloaded the image from my own server again and will now try setting up a fresh Sonoma VM using it.

**Comment by mc510** [comment]
FWIW, I am using latest VMware Workstation Pro, with unlocker applied. Sounds like @autra is using VirtualBox.

**Comment by Pyenb** [comment]
Nope, installer seems to be damaged. I just got the same error message in Proxmox. I created the ISO both times using [MIST](https://github.com/ninxsoft/Mist)

So either I will try again using MIST or create it manually. Give me a minute and I'll try and sort everything out.

**Comment by Pyenb** [comment]
I am at a loss right now. I created two new ISOs using MIST and by manually converting the installer and I got the same error both times when trying to set-up a new VM using them. I am starting to think that it may be a problem with my VM for whatever reason.

No worries, I will keep you updated on this, as soon as I figure out why it isn't working.

**Comment by Pyenb** [comment]
Hey, sorry that I didn't figure it out anymore. I will take another look at it as soon as I get home from work and set up a fresh VM to try this on

**Comment by autra** [comment]
@Pyenb No worries, you own us nothing :-) Thanks for this repo!

**Comment by mc510** [comment]
Most discussions that I've found suggest that this problem has something to do with an outdated digital certificate on the installer, with the solution being to set back the system date of macOS before it begins the main installation stage. Do you have notes on when you created the installer images? I'd try setting the system date to a few days after that creation date. (FWIW I unsuccessfully tried Ventura and Sonoma using current date, and set back to a few months after each was originally released, but perhaps the date has to be closer to the actual date that the installer was created?)

**Comment by Pyenb** [comment]
Hm, never heard of that. I'm not that big of a Mac guy, just wanted a VM to test some stuff out, which lead to this repo. But I will test this out and see if anything changes.

**Comment by Pyenb** [comment]
Hey @mc510, you seem to be onto something! I tried setting my RTC start date in Proxmox to `2024-10-06T00:00:00` and the install worked just fine. I will reupload the ISO now. Maybe someone else can test if this works for them too 👍

**Comment by Pyenb** [comment]
Hey @mc510, you may be onto something! I recreated another ISO installer and set the Proxmox RTC start date to `2025-10-06T00:00:00` in the new VM and the install worked just fine. So I don't know if that has really something to do with the certificates or with the ISO itself.

Anyways, I will upload it again and then maybe someone can tell me if they have any luck with it. I will also add Gofile downloads throughout the day, as they will be faster than my server.

**Comment by mc510** [comment]
Hey, forgot to follow up, but I had success with your new Sonoma ISO. Installation completed normally, and the system seems to be running properly. Thanks for your help with the ISOs :)

**Comment by Pyenb** [comment]
Glad to hear, thanks for the feedback 😁
