### ISSUE TITLE
Mac Os Sequoia 15

### ISSUE THREAD

**Issue by ZM71** [Pyenb/macOS-ISOs#11]
My wallpaper is white and when you click anywhere on the desktop it goes back to the app you have open, for instance i have settings and click it opens restarting vm does not work and the wallpaper instantly disappear when changing it.

**Comment by Pyenb** [comment]
Sorry, but i can't help with that. All I do is provide ISO files, not give any support with the OS itself. Also, if other people would've had this problem, I'm sure that there would already be reports👍

**Comment by ZM71** [comment]
i fixed it the dynamic wallpaper is not supported in the VM

**Comment by ZM71** [comment]
solved

**Comment by ZM71** [comment]
solved by choosing a static wallpaper instead of dynamic if your computer does not support 3d acceleration.
