### ISSUE TITLE
Torrent seeds

### ISSUE THREAD

**Issue by ferre-156** [Pyenb/macOS-ISOs#12]
Hi, i'm trying to download one of these iso's but every time i start the download on qBitTorrent it stalls cause there are no seeds. Are there preferred time slots to download this or the problem is mine? I use European time, so maybe when i try to download, every seed is asleep

**Comment by ZM71** [comment]
try using another program like U torrent.

**Comment by Pyenb** [comment]
What torrent are you trying to download? I am constantly seeding from 2 seperate servers, so there should always be at least one available seeder. Also check again if maybe your connection is blocked by your ISP and try downloading it again with a VPN.

**Comment by ZM71** [comment]
Proton has a cheap and unlimited vpn

**Comment by ZM71** [comment]
https://protonvpn.com/pricing
