### ISSUE TITLE
Torrent speed below 200kb/s

### ISSUE THREAD

**Issue by ZM71** [Pyenb/macOS-ISOs#15]
The latest mac does not start or download correctly.

**Comment by Pyenb** [comment]
Well, that's just how torrenting is. With too little seeders, it's gonna be slow. But I am still confused, as I have 2 servers seeding them 24/7 and it's showing me 7 current seeders.

So maybe you just hit a bad time or something else. Are you using a VPN or anything like that?

**Comment by ZM71** [comment]
Maybe it takes some time for the speed to reach me, I tried again and the speed was faster.

**Comment by ZM71** [comment]
Maybe it takes some time for the speed to reach me, I tried again and the speed was faster.

**Comment by ZM71** [comment]
The speed seems to work now.
