### ISSUE TITLE
[Suggustion] Better download speeds

### ISSUE THREAD

**Issue by bluekyeet** [Pyenb/macOS-ISOs#2]
Since you're running on a cheap Contabo VPS there's not much you can really do about the speed. I suggest you to switch to a seed-box and make it available to torrent instead. I could help seeding the torrent. I also have some extra OneDrive which I can upload the ISOs to :) I just wanna help you out

**Comment by Pyenb** [comment]
Hey there, just a quick update. I've added torrent links for every file, and they are currently uploading to RapidSeedbox, which should make it a lot faster. Feel free to download and seed them as well! I'd prefer to cancel the Seedbox as soon as enough people are seeding 😁

They are currently seeding from the same Storage-VPS, so until then, the speed won't be great.

**Comment by bluekyeet** [comment]
I'll get my VPN and torrent client setup in a few hours! My uploads speeds aren't that fast but it could contribute a fair bit.

**Comment by Pyenb** [comment]
No worries. As I said, I will leave it seeding for now from both machines.

**Comment by bluekyeet** [comment]
I've setup everything and got everything downloaded to my server. Right now I'm seeding. I did have to limit my speeds to 5 MB/S in the day time so that I still have extra bandwidth for other things I do but when it's not limited it's going to be at 10 MB/S max. I also limited the max amount of peers as my router just throttles when there's too much connections.
