### ISSUE TITLE
VM only? 

### ISSUE THREAD

**Issue by Momo90k** [Pyenb/macOS-ISOs#3]
Are these iso files for a VM only or for computer too?

**Comment by bluekyeet** [comment]
I'm pretty sure these can work for VMs and actual machines. Just keep in mind that if you're going to install this on a none Apple device or a VM it may be a hassle to get drivers working and to even get it booted.

**Comment by Pyenb** [comment]
These are mostly for VM's. As @bluekyeet said, if you wanna install this on actual hardware, you will need to look into [Hackintosh](https://hackintosh.com/).

**Comment by Momo90k** [comment]
I want to install on a MacBook

**Comment by Pyenb** [comment]
Then you should follow the official guides if you want to upgrade. Or check out https://github.com/ninxsoft/Mist. With that you can create a MacOS installer as an Mac application.
