### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by ZM71** [Pyenb/macOS-ISOs#4]
Hacking-tosh using these iso files?

**Comment by Pyenb** [comment]
Take a look at [this issue](https://github.com/Pyenb/macOS-ISOs/issues/3). As mentioned, probably possible, but not without any hastle. Look into "official" Hackintosh guides and see what Images they recommend. I am not experienced with them, so I cannot tell.

**Comment by ZM71** [comment]
it works
