### ISSUE TITLE
macos big sur installer broken

### ISSUE THREAD

**Issue by KWShop-team** [Pyenb/macOS-ISOs#7]
I have error while installing mac os and its a broken installer. can someone help?

**Comment by Pyenb** [comment]
Seems to be the same problem as here: https://github.com/Pyenb/macOS-ISOs/issues/1

I will take a look at it and reupload a new ISO. Also to now have duplicate threads, lets continue in this one:

https://github.com/Pyenb/macOS-ISOs/issues/6
