### ISSUE TITLE
MacOS Server for Monterey 

### ISSUE THREAD

**Issue by ericrowan** [Pyenb/macOS-ISOs#9]
Wasn't able to find this anywhere on my own. I believe the version would be around 5.12 or something. Many thanks!

**Comment by Pyenb** [comment]
Hey there, sorry I didn't see your message. But imma take a look later if i can create that ISO. MIST doesn't seem to have it, but shouldn't be a problem as long as I can find the installer files somewhere to convert it manually.

**Comment by Pyenb** [comment]
Ok, so I am not really familiar with all of this. But it seems like MacOS Server isn't it's own Version/ISO, but just a program that you install on top of an install using the App store. 

But with it being discontinued and and apparently having a license system, you'll have to look if you can still install it somehow.

https://support.apple.com/en-us/101601

**Comment by ericrowan** [comment]
Hey, I really appreciate that you looked into this. Cheers.
